### ISSUE TITLE
Feature: Support web platform

### ISSUE THREAD

**Issue by carlos-cubas** [christianascone/expo-stripe-checkout-sca#1]
@christianascone the timeliness of this package cannot be understated.  I was literally about to embark on wrapping @briansztamfaters code myself.  So thank you for this!.

Now my usecase is slightly different in that we support ios, android & web with a single codebase.  We have been using react-native-web to achieve this.

I was very quickly able to take your codebase and make it work within our app and support web, i've not extensively tested it, but I wanted to share my learnings with you, with the intent of making some design decisions around how I could contribute these changes back into this package via a PR.

It is actually incredibly simple, all i needed to do is to replace WebView & Modal with some react-native-web alternatives and everything worked out.  

```ts
import React, {Component} from 'react';
import WebView from 'react-native-web-webview';
import Modal from 'modal-enhanced-react-native-web';
import {
    Platform,
    StyleProp,
    StyleSheet,
    Text,
    TextStyle,
    TouchableOpacity,
    ViewStyle
} from 'react-native';
```

Now the question is how should I go about designing the swapping of these underlying dependencies so things are transparent to consumers of this package? FYI i'm brand new to the react, react-native, react-native-web & expo world, if you have some links you can send me I can read and make a proposal based on that.

**Comment by christianascone** [comment]
Hi @carlos-cubas 
What you say is really interesting and web compatibility would be very useful.
I'm brand new too to react/expo, but in another my simple project I faced this issue with a `webpack.config.js` like [this one](https://github.com/christianascone/React-Native-Expo-Template/blob/master/webpack.config.js).
```javascript
...
resolve: {
            alias: {
                "react-native/Libraries/Renderer/shims/ReactNativePropRegistry":
                    "react-native-web/dist/modules/ReactNativePropRegistry",
                "react-native": "react-native-web",
                'react-native-maps': 'react-native-web-maps',
            }
        },
...
```

Try with aliases for web components.

**Comment by carlos-cubas** [comment]
@christianascone wanted to share some further learnings.... I would mark the web support not production ready/viable. 

I encountered a fundamental problem as I was attempting to run the integration in Production.  The stripe js sdk would complain that https was required for production. This led to a lot of head scratching since the website was deployed using https.

Long story short, the reason for this is that react-native-web-webview internally uses an <iframe srcDoc="" />. This solely wouldn't be a problem, but the stripe sdk detects the use of https by parsing window.location

This breaks the integration since the window.location inside the iframe created with srcDoc is equal to "about:html" in chrome at least.

We have taken a shortcut for now and dropped the webview to avoid the iframe. We will be coming back to this issue in the future to create a better integration.
